In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Reading dataset

In [2]:
iris = load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

### Preparing dataset

In [5]:
dataset = pd.DataFrame(data = iris.data, columns = iris.feature_names)

In [6]:
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
dataset['target'] = iris.target

In [8]:
dataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [9]:
dataset['target'].unique()

array([0, 1, 2])

### Removing class **2** for binary classification

In [10]:
dataset_binary = dataset[dataset['target'] != 2]

In [11]:
dataset_binary.target.unique()

array([0, 1])

### Dividing our dataset into dependent and independent features

In [12]:
X = dataset.iloc[:, :-1] # Independent features
y = dataset.iloc[:, -1] # Dependent feature

In [13]:
X.shape, y.shape

((150, 4), (150,))

### Splitting the dataset in train and test datasets

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 47)

In [15]:
X_train.shape, y_train.shape

((120, 4), (120,))

In [16]:
X_test.shape, y_test.shape

((30, 4), (30,))

### Scaling the data

In [17]:
scaler = StandardScaler()

In [18]:
X_train_scaled = scaler.fit_transform(X_train)

In [19]:
X_test_scaled = scaler.transform(X_test)

### Model training

In [20]:
logistic_classifier = LogisticRegression()

In [21]:
logistic_classifier.fit(X_train_scaled, y_train)

LogisticRegression()

In [22]:
logistic_classifier.predict_proba(X_test_scaled)

array([[9.82531527e-01, 1.74683318e-02, 1.41110952e-07],
       [9.82462521e-01, 1.75373271e-02, 1.52018393e-07],
       [4.48979012e-02, 8.86373166e-01, 6.87289325e-02],
       [9.86568574e-01, 1.34311406e-02, 2.85935626e-07],
       [9.96267565e-01, 3.73239769e-03, 3.75958375e-08],
       [1.51389455e-06, 1.93577222e-02, 9.80640764e-01],
       [8.19014556e-02, 8.64008522e-01, 5.40900228e-02],
       [3.26214565e-05, 3.08321441e-02, 9.69135234e-01],
       [2.76945263e-02, 8.89283365e-01, 8.30221085e-02],
       [9.81814410e-01, 1.81853724e-02, 2.17175454e-07],
       [5.83073968e-04, 2.26053023e-01, 7.73363903e-01],
       [9.72347698e-01, 2.76518883e-02, 4.13942508e-07],
       [3.52521362e-02, 8.98617780e-01, 6.61300835e-02],
       [6.90016793e-05, 7.69823428e-02, 9.22948656e-01],
       [3.72800167e-03, 3.89505485e-01, 6.06766513e-01],
       [1.80963821e-05, 4.69182443e-02, 9.53063659e-01],
       [4.23470492e-03, 9.68229846e-01, 2.75354490e-02],
       [9.37653539e-01, 6.23456

### Prediction

In [23]:
y_pred_test = logistic_classifier.predict(X_test_scaled)

### Confusion Matrix, Accuraccy Score, Classification Report

In [24]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_test))

Confusion Matrix:
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]


In [25]:
print("Accuracy Score: ", accuracy_score(y_test, y_pred_test))

Accuracy Score:  0.9666666666666667


In [26]:
print("------------------Classification Report------------------\n", classification_report(y_test, y_pred_test))

------------------Classification Report------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.88      1.00      0.93         7
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



### Hyperparameter Tuning

In [27]:
parameters = {
    'penalty' : ('l1', 'l2', 'elasticnet', None),
    'C' : (0.5, 1, 5, 10, 20)
}

#### GridSearchCV

In [28]:
classifier = LogisticRegression()
grid_search_cv_clf = GridSearchCV(classifier, param_grid = parameters, cv = 5)

In [29]:
grid_search_cv_clf.fit(X_train_scaled, y_train)

c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': (0.5, 1, 5, 10, 20),
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [30]:
grid_search_cv_clf.cv_results_.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_C', 'param_penalty', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [31]:
grid_search_cv_clf.best_params_

{'C': 5, 'penalty': 'l2'}

In [32]:
grid_search_cv_best_clf = grid_search_cv_clf.best_estimator_

In [33]:
y_pred_test_grid_search = grid_search_cv_best_clf.predict(X_test_scaled)

In [34]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_test_grid_search))

Confusion Matrix:
 [[11  0  0]
 [ 0  7  0]
 [ 0  0 12]]


In [35]:
print("Accuracy Score: ", accuracy_score(y_test, y_pred_test_grid_search))

Accuracy Score:  1.0


In [36]:
print(
        "------------------Classification Report------------------\n",
        classification_report(y_test, y_pred_test_grid_search)
)

------------------Classification Report------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



#### RandomizedSearchCV

In [37]:
classifier = LogisticRegression()
randomized_search_cv_clf = RandomizedSearchCV(classifier, param_distributions = parameters, cv = 5)

In [38]:
randomized_search_cv_clf.fit(X_train_scaled, y_train)

c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\SOUMYAPANJA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:1181: UserWarning: Setting penalty=None

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': (0.5, 1, 5, 10, 20),
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [39]:
randomized_search_cv_clf.cv_results_.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_penalty', 'param_C', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [40]:
randomized_search_cv_clf.best_params_

{'penalty': 'l2', 'C': 5}

In [41]:
randomized_search_cv_best_clf = randomized_search_cv_clf.best_estimator_

In [42]:
y_pred_test_randomized_search = randomized_search_cv_best_clf.predict(X_test_scaled)

In [43]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_test_randomized_search))

Confusion Matrix:
 [[11  0  0]
 [ 0  7  0]
 [ 0  0 12]]


In [44]:
print("Accuracy Score: ", accuracy_score(y_test, y_pred_test_randomized_search))

Accuracy Score:  1.0


In [45]:
print(
        "------------------Classification Report------------------\n",
        classification_report(y_test, y_pred_test_randomized_search)
)

------------------Classification Report------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

