In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 4, (4, 3))

In [3]:
arr

array([[1, 1, 2],
       [3, 2, 3],
       [3, 1, 3],
       [2, 1, 3]])

In [4]:
arr.flatten()

array([1, 1, 2, 3, 2, 3, 3, 1, 3, 2, 1, 3])

In [5]:
arr.shape

(4, 3)

In [6]:
arr.ndim

2

In [10]:
arr_expand = np.expand_dims(arr, axis = 0)

In [11]:
arr_expand

array([[[1, 1, 2],
        [3, 2, 3],
        [3, 1, 3],
        [2, 1, 3]]])

In [12]:
arr_expand.shape

(1, 4, 3)

In [13]:
arr_expand.ndim

3

In [14]:
arr_expand = np.expand_dims(arr, axis = 1)

In [15]:
arr_expand

array([[[1, 1, 2]],

       [[3, 2, 3]],

       [[3, 1, 3]],

       [[2, 1, 3]]])

In [16]:
arr_expand.shape

(4, 1, 3)

In [17]:
arr_expand.ndim

3

In [18]:
arr_expand

array([[[1, 1, 2]],

       [[3, 2, 3]],

       [[3, 1, 3]],

       [[2, 1, 3]]])

In [19]:
arr_squeeze = arr_expand.squeeze()

In [20]:
arr_squeeze

array([[1, 1, 2],
       [3, 2, 3],
       [3, 1, 3],
       [2, 1, 3]])

In [21]:
arr_squeeze.shape

(4, 3)

In [22]:
arr_squeeze.ndim

2

In [25]:
arr_squeeze

array([[1, 1, 2],
       [3, 2, 3],
       [3, 1, 3],
       [2, 1, 3]])

In [26]:
np.repeat(arr_squeeze, 3) # repeats each element 3 times

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 3, 1,
       1, 1, 3, 3, 3, 2, 2, 2, 1, 1, 1, 3, 3, 3])

In [27]:
arr_squeeze

array([[1, 1, 2],
       [3, 2, 3],
       [3, 1, 3],
       [2, 1, 3]])

In [29]:
np.roll(arr_squeeze, 2) # shifted each element by two

array([[1, 3, 1],
       [1, 2, 3],
       [2, 3, 3],
       [1, 3, 2]])

In [30]:
np.diag(arr_squeeze)

array([1, 2, 3])

In [32]:
arr = np.array([1, 2, 3, 4])

In [33]:
np.diag(arr)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
arr1 = np.random.randint(1, 4, (4, 3))
arr2 = np.random.randint(1, 4, (4, 3))

In [36]:
arr1

array([[2, 1, 1],
       [3, 2, 2],
       [1, 1, 1],
       [1, 2, 3]])

In [37]:
arr2

array([[1, 2, 3],
       [3, 3, 3],
       [3, 2, 3],
       [3, 3, 2]])

In [38]:
arr1 % arr2

array([[0, 1, 1],
       [0, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [39]:
arr1 ** arr2

array([[ 2,  1,  1],
       [27,  8,  8],
       [ 1,  1,  1],
       [ 1,  8,  9]])

In [40]:
arr1 & arr2

array([[0, 0, 1],
       [3, 2, 2],
       [1, 0, 1],
       [1, 2, 2]])

In [41]:
~arr1

array([[-3, -2, -2],
       [-4, -3, -3],
       [-2, -2, -2],
       [-2, -3, -4]])

In [42]:
arr1 > arr2

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [43]:
np.array(["hello", "world"])

array(['hello', 'world'], dtype='<U5')

In [44]:
arr = np.array(["hello", "world"])

In [45]:
type(arr)

numpy.ndarray

In [46]:
np.char.upper(arr)

array(['HELLO', 'WORLD'], dtype='<U5')

In [47]:
np.char.title(arr)

array(['Hello', 'World'], dtype='<U5')

In [48]:
np.char.capitalize(arr)

array(['Hello', 'World'], dtype='<U5')

In [49]:
np.sin(arr_squeeze)

array([[0.84147098, 0.84147098, 0.90929743],
       [0.14112001, 0.90929743, 0.14112001],
       [0.14112001, 0.84147098, 0.14112001],
       [0.90929743, 0.84147098, 0.14112001]])