In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3, 4]

In [3]:
np.array(lst)

array([1, 2, 3, 4])

In [4]:
type(np.array(lst))

numpy.ndarray

In [5]:
np.asarray(lst)

array([1, 2, 3, 4])

In [6]:
type(np.asarray(lst))

numpy.ndarray

In [7]:
np.asanyarray(lst)

array([1, 2, 3, 4])

In [8]:
type(np.asanyarray(lst))

numpy.ndarray

In [9]:
np.matrix(lst) # matrix is 2d, therefore it is a subset of ndarray

matrix([[1, 2, 3, 4]])

In [10]:
type(np.matrix(lst))

numpy.matrix

In [11]:
mat = np.matrix(lst)

In [12]:
mat

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(mat) # doesn't convert to ndarray, as matrix is form (or subset of array)

matrix([[1, 2, 3, 4]])

In [14]:
np.fromfunction(lambda i, j: i == j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [15]:
np.fromfunction(lambda i, j: i * j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [16]:
iterable = (i * i for i in range(5)) # this is a generator

In [17]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [18]:
np.fromstring("1 2 3 4", sep = " ")

array([1., 2., 3., 4.])

In [19]:
arr = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

In [20]:
arr

array([[1, 2],
       [3, 4]])

In [21]:
arr.ndim

2

In [22]:
arr.size

4

In [23]:
arr.shape

(2, 2)

In [24]:
arr.dtype

dtype('int32')

In [25]:
np.arange(0.3, 5.7)

array([0.3, 1.3, 2.3, 3.3, 4.3, 5.3])

In [26]:
np.arange(0.3, 5.7, 0.43)

array([0.3 , 0.73, 1.16, 1.59, 2.02, 2.45, 2.88, 3.31, 3.74, 4.17, 4.6 ,
       5.03, 5.46])

In [27]:
np.linspace(1, 10 , 13)

array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ,  4.75,  5.5 ,  6.25,  7.  ,
        7.75,  8.5 ,  9.25, 10.  ])

In [28]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
ones = np.ones((4, 2))

In [31]:
ones + 5

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [32]:
ones * 4

array([[4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.]])

In [33]:
np.empty((3, 4, 3))

array([[[1.14303352e-311, 1.19069821e-321, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.16097020e-028],
        [1.26087994e-076, 2.80061839e-028, 1.48374082e-076],
        [1.04917183e-153, 5.23081515e-143, 1.88560370e+185]],

       [[1.14332092e-071, 2.64646614e-032, 4.17824338e-062],
        [7.81338932e-144, 3.59751658e+252, 1.46901661e+179],
        [8.37404147e+242, 4.31999013e-096, 4.82337723e+228],
        [2.44214956e-052, 5.04775598e-038, 4.76067011e-090]],

       [[4.01395478e-057, 1.55978950e+161, 5.04621343e+180],
        [1.94918963e-153, 3.40805478e+175, 2.34059419e-057],
        [4.71206487e-062, 6.49419847e+169, 1.04915079e-153],
        [9.08366791e+223, 5.82381891e-144, 1.88239011e-321]]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [37]:
np.logspace(1, 5, 10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [42]:
np.random.randn(4, 3, 2)

array([[[ 0.34097771,  0.31383484],
        [-1.42743593,  1.64706462],
        [ 0.23339057,  2.28527059]],

       [[ 1.61014769,  0.45966809],
        [ 0.39964818, -0.06297825],
        [-1.56916047, -1.3813542 ]],

       [[ 1.50112671, -1.05951032],
        [ 0.11856914, -1.71074586],
        [ 0.3751491 , -0.49788228]],

       [[-2.24137486, -0.15194992],
        [-0.05374553,  1.29809962],
        [ 0.13030744, -0.0221726 ]]])

In [41]:
arr = np.random.randn(4, 3, 2)

In [43]:
arr

array([[[ 0.24597397,  1.21126709],
        [-0.72395206,  0.20336668],
        [-0.09419046,  0.68208891]],

       [[ 0.4503457 ,  0.52210327],
        [ 0.64428654, -0.10173462],
        [-0.72323544, -1.55740758]],

       [[ 0.2716118 ,  1.03927883],
        [ 1.26939191,  0.48259369],
        [ 1.59185894, -1.01068585]],

       [[ 0.43959793,  0.95738199],
        [ 0.84544768, -1.07859793],
        [-0.69872439, -0.78835723]]])

In [45]:
arr = np.random.randn(4, 3)

In [46]:
import pandas as pd

In [47]:
pd.DataFrame(arr)

0         1         2
0  1.732755  1.042902  1.022707
1  0.243364  0.270699  0.134914
2 -1.176222 -0.433597 -0.639560
3 -0.375362 -0.977452  0.540691

In [48]:
np.random.rand(4, 3)

array([[0.4512205 , 0.23002828, 0.29297751],
       [0.89642576, 0.7040104 , 0.4617154 ],
       [0.41637068, 0.89110595, 0.08715313],
       [0.07257408, 0.15577189, 0.43408872]])

In [50]:
np.random.randint(2, 10, (4, 3))

array([[8, 4, 4],
       [8, 5, 3],
       [2, 9, 8],
       [7, 2, 4]])

In [52]:
pd.DataFrame(np.random.randint(2, 10, (4, 3))).to_csv('test.csv')

In [53]:
arr

array([[ 1.73275465,  1.04290184,  1.02270699],
       [ 0.24336443,  0.27069874,  0.13491398],
       [-1.17622194, -0.43359695, -0.63955988],
       [-0.37536163, -0.97745235,  0.54069073]])

In [54]:
arr.reshape(6, 2)

array([[ 1.73275465,  1.04290184],
       [ 1.02270699,  0.24336443],
       [ 0.27069874,  0.13491398],
       [-1.17622194, -0.43359695],
       [-0.63955988, -0.37536163],
       [-0.97745235,  0.54069073]])

In [55]:
arr

array([[ 1.73275465,  1.04290184,  1.02270699],
       [ 0.24336443,  0.27069874,  0.13491398],
       [-1.17622194, -0.43359695, -0.63955988],
       [-0.37536163, -0.97745235,  0.54069073]])

In [56]:
arr.reshape((6, -1))

array([[ 1.73275465,  1.04290184],
       [ 1.02270699,  0.24336443],
       [ 0.27069874,  0.13491398],
       [-1.17622194, -0.43359695],
       [-0.63955988, -0.37536163],
       [-0.97745235,  0.54069073]])

In [59]:
arr.reshape((6, -1234))

array([[ 1.73275465,  1.04290184],
       [ 1.02270699,  0.24336443],
       [ 0.27069874,  0.13491398],
       [-1.17622194, -0.43359695],
       [-0.63955988, -0.37536163],
       [-0.97745235,  0.54069073]])

In [60]:
arr

array([[ 1.73275465,  1.04290184,  1.02270699],
       [ 0.24336443,  0.27069874,  0.13491398],
       [-1.17622194, -0.43359695, -0.63955988],
       [-0.37536163, -0.97745235,  0.54069073]])

In [62]:
arr[1:3, 2]

array([ 0.13491398, -0.63955988])

In [63]:
arr = np.random.randint(1, 100, (5, 6))

In [64]:
arr

array([[57, 32,  2, 42, 69, 14],
       [30, 67,  6, 45, 93, 78],
       [97,  1, 71, 15, 70, 14],
       [50, 72, 75, 94, 12, 36],
       [97, 87, 30, 57, 54, 80]])

In [65]:
arr > 50

array([[ True, False, False, False,  True, False],
       [False,  True, False, False,  True,  True],
       [ True, False,  True, False,  True, False],
       [False,  True,  True,  True, False, False],
       [ True,  True, False,  True,  True,  True]])

In [66]:
arr[arr > 50]

array([57, 69, 67, 93, 78, 97, 71, 70, 72, 75, 94, 97, 87, 57, 54, 80])

In [68]:
arr

array([[57, 32,  2, 42, 69, 14],
       [30, 67,  6, 45, 93, 78],
       [97,  1, 71, 15, 70, 14],
       [50, 72, 75, 94, 12, 36],
       [97, 87, 30, 57, 54, 80]])

In [67]:
arr[2:3, [1, 2, 3]]

array([[ 1, 71, 15]])

In [69]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [70]:
arr1

array([[2, 1, 1],
       [2, 2, 2],
       [2, 2, 1]])

In [71]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [72]:
arr1 + arr2

array([[4, 3, 2],
       [3, 3, 3],
       [4, 4, 2]])

In [75]:
arr1 * arr2 # element wise multiplication

array([[4, 2, 1],
       [2, 2, 2],
       [4, 4, 1]])

In [76]:
arr1 @ arr2 # matrix multiplication

array([[ 7,  7,  4],
       [10, 10,  6],
       [ 8,  8,  5]])

In [77]:
arr1 / 0

C:\Users\SOUMYA~1\AppData\Local\Temp/ipykernel_12652/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [78]:
arr1 ** 2

array([[4, 1, 1],
       [4, 4, 4],
       [4, 4, 1]])

In [84]:
arr = np.zeros((3, 4))

In [85]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
row = np.array([1, 2, 3, 4])

In [87]:
row

array([1, 2, 3, 4])

In [89]:
arr + row # broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [91]:
arr = np.zeros((4, 3))

In [92]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [94]:
# arr + row
# throws error as arr is (4, 3) and row is (4,)

In [95]:
arr = np.zeros((4, 4))
row = np.array([[1, 2, 3, 4]])

In [96]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
row

array([[1, 2, 3, 4]])

In [98]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [99]:
arr + row.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])