In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)

In [4]:
arr

array([ 6,  7, 18,  2, 17, 12,  2,  6, 17, 18])

In [5]:
np.sort(arr)

array([ 2,  2,  6,  6,  7, 12, 17, 17, 18, 18])

In [7]:
arr

array([ 6,  7, 18,  2, 17, 12,  2,  6, 17, 18])

In [11]:
np.searchsorted(arr, 8) # search the index from start, where 8 can be inserted to make the array sorted.
# it assumes the array is sorted

2

In [12]:
arr = np.random.randint(0, 2, 10)

In [13]:
arr

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 1])

In [14]:
np.nonzero(arr)

(array([0, 1, 2, 3, 4, 6, 9], dtype=int64),)

In [15]:
np.count_nonzero(arr)

7

In [16]:
arr = np.random.randint(1, 20, 10)

In [17]:
arr

array([19,  3,  6, 16,  1,  1, 12, 13,  2,  3])

In [18]:
np.where(arr > 5)

(array([0, 2, 3, 6, 7], dtype=int64),)

In [19]:
np.extract(arr > 5, arr)

array([19,  6, 16, 12, 13])

In [20]:
arr.byteswap()

array([318767104,  50331648, 100663296, 268435456,  16777216,  16777216,
       201326592, 218103808,  33554432,  50331648])

In [21]:
arr

array([19,  3,  6, 16,  1,  1, 12, 13,  2,  3])

In [22]:
# Deep copy
copy = arr.copy()

In [24]:
# shallow copy
copy = arr.view() # same as copy = arr

In [26]:
import numpy.matlib as nm # matrix library

In [27]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.zeros((5, 4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
nm.eye(4, 3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [32]:
arr1 = np.random.randint(1, 5, (2, 2))
arr2 = np.random.randint(1, 5, (2, 2))

In [33]:
arr1

array([[1, 1],
       [4, 3]])

In [34]:
arr2

array([[3, 1],
       [4, 2]])

In [35]:
np.dot(arr1, arr2)

array([[ 7,  3],
       [24, 10]])

In [36]:
arr1 @ arr2

array([[ 7,  3],
       [24, 10]])