In [25]:
import torch
import numpy as np

In [2]:
x = torch.rand(3, 2)
x # So here x is a tensor

tensor([[0.6128, 0.6298],
        [0.7654, 0.8156],
        [0.2065, 0.3986]])

In [3]:
y = torch.rand(3, 3)
y

tensor([[0.6997, 0.2663, 0.6270],
        [0.5421, 0.3644, 0.4328],
        [0.7411, 0.7014, 0.8373]])

In [4]:
print(x)
print(y)

tensor([[0.6128, 0.6298],
        [0.7654, 0.8156],
        [0.2065, 0.3986]])
tensor([[0.6997, 0.2663, 0.6270],
        [0.5421, 0.3644, 0.4328],
        [0.7411, 0.7014, 0.8373]])


In [5]:
torch.zeros(5,3) # tensor of zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.tensor([5.5, 3]) # tensor from existing data

tensor([5.5000, 3.0000])

In [8]:
print(x.size())

torch.Size([3, 2])


In [10]:
x = torch.randn(4, 4)
y = torch.randn(4, 4)
print(x)
print(y)
print(torch.add(x, y))

tensor([[ 0.3339,  0.5979, -0.3958, -0.8587],
        [ 0.2980, -1.3512,  0.3161,  1.3519],
        [ 1.0631, -0.9918, -0.5240,  1.4035],
        [-0.1323, -0.2221, -0.3851, -1.0911]])
tensor([[-0.0190,  0.1966,  0.1072,  0.3701],
        [-1.2458,  0.2865, -0.0987,  0.3326],
        [-0.5450, -0.9331, -0.3407, -0.3952],
        [ 0.2904,  0.9385,  0.6118, -0.4760]])
tensor([[ 0.3149,  0.7945, -0.2886, -0.4886],
        [-0.9477, -1.0647,  0.2174,  1.6846],
        [ 0.5181, -1.9249, -0.8647,  1.0084],
        [ 0.1581,  0.7164,  0.2267, -1.5671]])


In [11]:
print(x[:,1])

tensor([ 0.5979, -1.3512, -0.9918, -0.2221])


In [13]:
z = x.view(16) # resizing the tensor
z

tensor([ 0.3339,  0.5979, -0.3958, -0.8587,  0.2980, -1.3512,  0.3161,  1.3519,
         1.0631, -0.9918, -0.5240,  1.4035, -0.1323, -0.2221, -0.3851, -1.0911])

In [18]:
x.view(-1, 8)

tensor([[ 0.3339,  0.5979, -0.3958, -0.8587,  0.2980, -1.3512,  0.3161,  1.3519],
        [ 1.0631, -0.9918, -0.5240,  1.4035, -0.1323, -0.2221, -0.3851, -1.0911]])

In [21]:
x = torch.randn(1, 8, 32, 24)
y = x.view(8, 2, -1, 3, 8)
print(x)

tensor([[[[ 0.4298, -0.0387,  0.3614,  ...,  0.9604,  0.5568, -1.2125],
          [-0.5872, -0.9058, -1.5563,  ..., -0.2778, -1.0230, -1.3838],
          [-1.7199,  0.4822, -1.2422,  ...,  0.6151, -0.3650,  0.7833],
          ...,
          [ 0.1092, -0.2798,  1.0581,  ..., -1.4954, -1.1535, -0.6871],
          [-0.3425, -1.3500, -0.1426,  ...,  0.3180,  0.2377,  0.4471],
          [-0.4743, -1.5047,  0.3092,  ..., -1.0592,  0.0052,  0.6302]],

         [[-0.2848, -0.0392,  0.4011,  ..., -0.5904, -0.4638, -0.1520],
          [ 0.7673,  0.7058, -0.7213,  ...,  0.5899,  0.3290,  0.8225],
          [ 1.5588, -0.2371, -1.2500,  ...,  2.0258,  1.2520,  0.1179],
          ...,
          [ 1.7566,  1.2643,  0.7454,  ...,  0.5283,  0.8159,  0.0333],
          [ 0.6394, -0.2788, -1.4422,  ..., -0.9491, -1.2034, -0.9706],
          [ 1.4708, -0.0711,  1.0308,  ...,  0.0088, -0.7964,  0.7519]],

         [[ 0.5430, -0.4277,  1.1370,  ...,  0.1163,  1.0422, -0.7353],
          [ 0.6910, -1.7483,  

In [22]:
print(y)

tensor([[[[[ 0.4298, -0.0387,  0.3614,  ...,  0.3011, -1.5788, -1.6502],
           [-0.9206, -0.2466, -1.1619,  ...,  0.0810,  0.8876,  0.8455],
           [-0.7266, -0.6891,  0.3223,  ...,  0.9604,  0.5568, -1.2125]],

          [[-0.5872, -0.9058, -1.5563,  ...,  0.7463, -0.2035, -0.0925],
           [ 1.6786, -1.6499,  1.0106,  ...,  0.7247, -2.0319, -1.0593],
           [ 0.5338,  1.3634,  0.8175,  ..., -0.2778, -1.0230, -1.3838]],

          [[-1.7199,  0.4822, -1.2422,  ...,  0.7211,  0.9426, -2.7649],
           [ 0.0134,  0.3402,  0.2387,  ...,  0.0059, -0.5762, -0.5147],
           [ 0.5608,  0.1552,  1.3304,  ...,  0.6151, -0.3650,  0.7833]],

          ...,

          [[-1.6280,  0.8108, -2.1560,  ..., -0.7494, -1.5992, -0.3392],
           [-0.4841,  1.2925, -0.2956,  ...,  0.2739,  0.7019, -0.5049],
           [-1.2141, -0.1565, -0.2031,  ...,  0.1117, -1.6899, -0.9021]],

          [[ 0.6207, -0.3309, -0.7417,  ..., -1.2169,  0.7605, -0.7264],
           [-0.0192,  1.466

In [23]:
print(y.size())

torch.Size([8, 2, 16, 3, 8])


In [27]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [28]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [29]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [30]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [37]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
res = torch.mm(mat1, mat2)
print(mat1)
print(mat2)

tensor([[ 1.7846,  0.9976, -1.1056],
        [-0.1649,  0.1260,  0.6689]])
tensor([[-0.8746, -1.0446, -1.7142],
        [-0.5427, -1.0640,  1.0665],
        [-1.1480,  0.0430,  1.6994]])


In [39]:
print(res)
print(res.size())

tensor([[-0.8329, -2.9731, -3.8741],
        [-0.6921,  0.0669,  1.5537]])
torch.Size([2, 3])


In [41]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
print(batch1)
print(batch2)

tensor([[[ 2.2349,  0.6537,  1.0872, -1.2130],
         [-0.1328,  1.7959,  0.5656, -0.0433],
         [ 0.0532, -0.2530, -0.0465,  0.4189]],

        [[ 0.1778,  0.2148, -0.4367, -0.2223],
         [-0.3718,  1.3588, -1.9622,  1.0916],
         [ 1.0979, -1.0441, -1.8419,  0.4198]],

        [[ 1.6410,  0.6082,  0.3725, -2.2592],
         [-0.7629, -1.3022, -0.3107, -0.1904],
         [ 0.2374,  0.0498,  0.0523, -0.9906]],

        [[-1.5884, -1.4156, -0.0125,  1.4523],
         [-0.0758, -0.7781, -1.2602,  0.0512],
         [-0.8516,  0.2264,  1.2995, -0.9397]],

        [[-0.7266,  0.8791, -0.7237, -0.3044],
         [ 1.2337, -0.1358, -0.5168,  2.1495],
         [-0.8774,  0.9596,  0.5898, -0.1790]],

        [[ 1.2286, -0.2746,  0.3138,  1.2756],
         [-0.9358, -0.3694,  0.0466, -0.7947],
         [-0.3843, -0.7412, -0.3785, -1.4292]],

        [[ 1.1322, -1.3037, -0.4511,  0.1268],
         [-0.1215, -1.0607,  0.0466, -0.2457],
         [-0.2506, -0.7938, -1.8581,  0.3603]],


In [42]:
print(res)
print(res.size())

tensor([[[-3.7559e+00, -1.4051e+00,  3.7462e-01, -5.5585e+00, -2.6042e-01],
         [-6.0610e-01,  1.1110e+00,  7.3057e-01, -1.9319e+00,  1.5612e+00],
         [-9.4158e-02, -4.1297e-01, -7.7016e-01,  5.1891e-01,  5.4394e-02]],

        [[ 7.4447e-02,  1.0100e-01,  7.3402e-01,  1.9727e-01,  1.0126e+00],
         [ 8.4756e-01, -7.0859e-01, -3.0216e+00,  8.7004e-02, -2.3064e-01],
         [ 1.2001e+00, -3.4483e+00, -1.5440e+00,  2.4945e-02,  2.1071e+00]],

        [[-1.0527e+00,  2.7049e+00,  7.6059e-01,  5.6937e-01,  2.3082e+00],
         [-3.1232e-01, -6.8941e-01, -2.9196e-01,  2.4510e+00,  1.4797e+00],
         [-6.0947e-01,  4.4874e-01, -1.6304e-01,  8.4396e-01,  8.9513e-01]],

        [[-7.1221e-01,  7.8016e-01, -2.0807e+00,  2.4167e+00,  2.3428e-01],
         [-7.3289e-01, -1.7643e-01, -1.9399e+00, -1.7155e-01,  1.1562e+00],
         [ 3.7163e+00,  1.3197e+00,  4.1601e+00,  1.6502e+00, -2.1222e+00]],

        [[-1.3540e-01, -1.7730e-01,  8.2800e-01,  9.5921e-01, -2.6019e-01],
    

In [47]:
x = torch.ones(2, 2)
y = torch.ones(2, 1)
w = torch.randn(2, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [52]:
p = torch.sigmoid(torch.mm(x, w) + b) # prediction
loss = -y * torch.log(p) - (1 - y) * torch.log(1 - p) # cross-entropy loss
cost = loss.mean() # the cost to minimize

In [53]:
cost.backward()

In [55]:
print(w.grad)
print(b.grad)

tensor([[-0.9828],
        [-0.9828]])
tensor([-0.9828])
